canvas=document.getElementById("myCanvas");
ctx= canvas.getContext("2d");
var color="cyan";
ctx.beginPath();
ctx.strokeStyle=color;
ctx.lineWidth=2;
ctx.arc(200, 200, 60, 0, 360);
ctx.stroke();
var color="black";
ctx.beginPath();
ctx.strokeStyle=color;
ctx.lineWidth=2;
ctx.arc(340, 200, 60, 0, 360);
ctx.stroke();
var color="red";
ctx.beginPath();
ctx.strokeStyle=color;
ctx.lineWidth=2;
ctx.arc(480, 200, 60, 0, 360);
ctx.stroke();
var color="yellow";
ctx.beginPath();
ctx.strokeStyle=color;
ctx.lineWidth=2;
ctx.arc(270, 270, 60, 0, 360);
ctx.stroke();
var color="green";
ctx.beginPath();
ctx.strokeStyle=color;
ctx.lineWidth=2;
ctx.arc(410, 270, 60, 0, 360);
ctx.stroke();